Support for the ESP-IDF framework
smol-rs/polling pull request #128
Opened 2023-08-03 18:56 UTC by ivmarkov

(This has been long supported in a [fork](https://github.com/smol-rs/polling/compare/master...esp-rs-compat:polling:master) of the `polling` crate, but the fork was against an ancient version. So I finally jumped the gun to rebase it against the latest `polling` and try to upstream now.)

ESP IDF already does support the `poll` syscall, so this PR is only necessary because - ESP IDF being an embedded OS (or toolkit?) - does not support anything process-related, including the `pipe` syscall.
 
However [it does support a subset of the `eventfd` syscall API](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/vfs.html#event-fds), so what this PR does is to augment the `poll` module - specifically for ESP IDF - with an alternative `eventfd` codepath to where `pipe` is usually utilized. The same idea (use `eventfd` for the ESP IDF) was I believe re-used by @jasta in the [recently upstreamed support for ESP IDF in tokio's reactor](https://github.com/tokio-rs/mio/pull/1692/files#diff-f9d8cbc0b569bc0ec06f40054daee6950e838fba27849dffefc3c74803118223L89).

In terms of changes, two main items:
* As per above, the `poll` module is augmented with alternative code-path based on `eventfd`
* I had to also update the `rustix` dependency from `0.37.X` to `0.38.X` as the support for ESP IDF in `rustix` (including the `eventfd` syscall) lands in the `0.38.X` version. I hope you don't mind and I noticed other crates in the `smol` ecosystem already use `rustix` `0.38.X` so I guess it was just a matter of time and somebody taking the effort to update it for this crate as well
  * The changes for the new `rustix` version are really mainly addressing latest `rustix` shuffling code around (the new `events` module). Two changes worth noting are [this one](https://github.com/smol-rs/polling/compare/master...esp-rs-compat:polling:espidf#diff-1aed9be8eb5b536b6f0da7ee8d523f7415dc55c02ba340c5dae388e891dfc75fR101) and [this one](https://github.com/smol-rs/polling/compare/master...esp-rs-compat:polling:espidf#diff-1aed9be8eb5b536b6f0da7ee8d523f7415dc55c02ba340c5dae388e891dfc75fR162) where I believe in the latter, the cast to `time_t` was incorrect in the first place.

2023-08-03 19:37 UTC, notgull requested changes
I don't like the way that the alternating `pipe`/`eventfd` code is scattered throughout the module. It would be better if there was a single `Notifier` type that contained either the pipe on non-ESP and the eventfd on ESP. I did a similar thing in `kqueue.rs` to switch between pipes and user events.

Looks good otherwise.

2023-08-03 19:41 UTC, ivmarkov commented
OK. Will schedule some time over the weekend to do that.

2023-08-04 02:28 UTC, daggerrz commented
@ivmarkov, this is a related: https://github.com/smol-rs/polling/pull/129

I rant into this while using your branch for embedded development and building tests for my MacOS host. The Rustix dependency update breaks some targets.

2023-08-04 03:16 UTC, notgull commented
I merged #123 because I don't want to build up changes that are going to get stale. Just a heads up. This also takes care of the rustix v0.38 port.

2023-08-04 03:56 UTC, daggerrz commented
Ah, thanks, did not see that it was already pending!

2023-08-04 05:30 UTC, ivmarkov commented
@notgull Two additional follow up questions:
* Looking at your[ unix domain socket `Notify` implementation in the `kqueue`](https://github.com/smol-rs/polling/blob/master/src/kqueue.rs#L356), it is pretty much identical in behavior to the pipe-based notification mechanism in the `poll` module, except based on unix domain sockets. Shall I re-base the one in `poll` that would be `#[cfg(not(target_os = "espidf"))]` to be also based on unix domain sockets (not sure these are available everywhere else?) or shall I keep it based on pipes, as it is now?
* If we go for domain sockets, do you want the domain socket impl somehow centralized and outside of `kqueue` and `poll` (not sure that's easily possible but I can try), or do you want to separate implementations - one in `kqueue` and one in `poll`?

I'm in favor of a minimal variant where `poll` still has its own, private implementation based on `pipe` (and `eventfd` for the ESP IDF) as this stuff is difficult to test with so many variants of polling and operating systems, but also would like to understand where you want to drive this in the end, so that I don't have to redo the PR multiple times.

2023-08-04 13:58 UTC, notgull commented
- Unfortunately `UnixStream` does not work on Fuchsia. As Fuchsia isn't technically Unix, `libstd` does not expose it. So pipes are necessary for this use case.
- I would prefer to keep the `Notifier` type in this module. The goal is to have each module be as self contained as possible. Not to mention, the code can't really be shared between Unix and Windows.

2023-08-04 21:49 UTC, ivmarkov commented
> * Unfortunately `UnixStream` does not work on Fuchsia. As Fuchsia isn't technically Unix, `libstd` does not expose it. So pipes are necessary for this use case.
> * I would prefer to keep the `Notifier` type in this module. The goal is to have each module be as self contained as possible. Not to mention, the code can't really be shared between Unix and Windows.

OK it should be ready for another review.
* I have run the unit tests for both the `pipe` based approach as well as the `eventfd` based one on Linux as it supports both approaches.
* The one weird thing I found is that Linux really wants the eventfd handle to be registered with `PollFlags::IN` - as documented actually, while ESP IDF doesn't care.

2023-08-04 23:59 UTC, notgull requested changes
Overall this looks good to me. Can you add a test to CI to make sure this code builds when targeting ESP-IDF? Even a simple `cargo check` would be enough.

Ignore the Wine and Cross failures in CI, they aren't your fault.

2023-08-05 05:27 UTC, ivmarkov commented
> Overall this looks good to me. Can you add a test to CI to make sure this code builds when targeting ESP-IDF? Even a simple `cargo check` would be enough.
> 
> Ignore the Wine and Cross failures in CI, they aren't your fault.

`cargo check` should be doable, yes, but with the following two caveats:
* Caveat 1: It will be a rust `nightly`-only exercise. The problem is, ESP IDF - being a Tier 3 target - does not get a pre-built STD by default. So we do need a command line like `rustup component add rust-src --toolchain nightly; cargo +nightly check --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort`, where the `-Zbuild-std` part is unfortunately a nightly-only feature of Cargo. 
* Caveat 2: The `eventfd` binding in `rustix` for ESP IDF specifically, just got merged [the other day](https://github.com/bytecodealliance/rustix/pull/769), and thus missed the 0.38.6 release, so it is only in `rustix`'s mainline. Let me actually open a PR against their repo for issuing another `rustix` point release

So if you are OK with 'Caveat 1`, yes, I'll work on that.

2023-08-05 06:47 UTC, ivmarkov commented
OK, CI is ready. For now (and until `rustix` 0.38.7 is released), `cargo check` for ESP IDF runs with the `rustix` dependency patched against its mainline (and there is a weird warning that the patched dependency is not used, but surely it is or else the build would've failed).

2023-08-05 14:19 UTC, notgull approved these changes
Thanks!

NetBSD failure looks spurious to me, not sure why that's happening.

2023-08-05 14:28 UTC, merged