feat: enable construct event constantly
smol-rs/polling pull request #140
Opened 2023-08-21 15:17 UTC by tisonkun

2023-08-21 15:29 UTC, tisonkun commented
Perhaps I can use a `const KEY: usize = 1` and `Event::readable(KEY)` and that should be fine.

Keep this PR open for ideas on whether we can make the event constructors themselves const.

2023-08-22 00:51 UTC, notgull requested changes
I think this would be a good addition to this crate.

2023-08-22 00:51 UTC, notgull commented on src/iocp/mod.rs
>          }
Fix the compile error by also making `AfdPollMask::empty()` constant.

2023-08-22 00:51 UTC, notgull commented on src/lib.rs
> +    pub const fn all(key: usize) -> Event {
You forgot to make the `poll.rs` version of `EventEmpty` `const`.

2023-08-22 00:58 UTC, tisonkun commented
Updated. Let's see if all the empty branches can be `const`.

2023-08-22 01:26 UTC, tisonkun commented
All tests passed. PTAL @notgull

2023-08-22 01:31 UTC, notgull approved these changes
Looks good to me!

2023-08-22 01:32 UTC, merged