Fix: replace is_connect_failed with is_err
smol-rs/polling pull request #189
Opened 2024-02-07 17:01 UTC by irvingoujAtDevolution

In linux, epoll, EPOLLHUP may happen even if no connection call is made. It would confuse callers for what is actually happening.
Replaced is_connect_failed, and we detect if connection failed by using the combination of is_err and is_interrupt, please see the example, tcp_client

2024-02-07 20:03 UTC, notgull requested changes
Unfortunately we can't change `is_connect_failed` as that would be a breaking change. So we have to keep the name the same there.

2024-02-07 20:26 UTC, irvingoujAtDevolution commented
> Unfortunately we can't change `is_connect_failed` as that would be a breaking change. So we have to keep the name the same there.

I apologize for my previous mistake. I would like to have your opinion on whether it is better to add `is_err`, mark `is_connect_fail` as deprecated, or simply keep using the same name but change the implementation.

I would argue that the first approach is better, as it aligns with the semantics it provides.

2024-02-10 17:54 UTC, notgull commented
> I apologize for my previous mistake. I would like to have your opinion on whether it is better to add `is_err`, mark `is_connect_fail` as deprecated, or simply keep using the same name but change the implementation.
> 
> I would argue that the first approach is better, as it aligns with the semantics it provides.

I'd argue that the first would be better.

2024-02-15 04:05 UTC, notgull requested changes

2024-02-15 04:05 UTC, notgull commented on examples/tcp_client.rs
> -use std::{io, net};
I would appreciate not changing this example and instead just wrapping the socket error bits in the configuration guards.

2024-02-15 04:05 UTC, notgull commented on examples/tcp_client.rs
> +    println!("testing bad socket");
If this is a functionality test it should be moved to be under the `tests` folder.

2024-02-15 04:05 UTC, notgull commented on src/lib.rs
> +    #[deprecated]
Please add a deprecation message here.

2024-02-22 20:03 UTC, irvingoujAtDevolution commented on src/lib.rs
> +    #[deprecated]
updated

2024-02-23 03:23 UTC, notgull commented on examples/tcp_client.rs
> -use std::{io, net};
Don't modify the Example too much; just make it so the `is_err`-specific code is guarded.

2024-02-29 14:22 UTC, irvingoujAtDevolution commented
please have a look again, I am not exactly sure if this is how you want it.

2024-03-02 03:35 UTC, notgull requested changes
Overall LGTM, just some minor considerations regarding docs.

2024-03-02 03:35 UTC, notgull commented on src/lib.rs
> +    /// note: in epoll, a tcp connection failure is indicated by EPOLLERR + EPOLLHUP, though just EPOLLERR is enough to indicate a connection failure.
```suggestion
    /// ## Caveats
    ///
    /// In `epoll`, a TCP connection failure is indicated by `EPOLLERR` + `EPOLLHUP`, though just `EPOLLERR` is enough to indicate a connection failure.
```

2024-03-02 03:35 UTC, notgull commented on src/lib.rs
> +    ///   }
Why is this block indented?

2024-03-02 03:35 UTC, notgull commented on src/lib.rs
> +    /// Returns `Some(true)` if the connection has failed, `Some(false)` if there is an error,
```suggestion
    /// ```  
    ///
    /// Returns `Some(true)` if the connection has failed, `Some(false)` if there is an error,
```

2024-03-15 17:49 UTC, irvingoujAtDevolution commented on src/lib.rs
> +    ///   }
updated, removed it

2024-03-16 17:42 UTC, notgull reviewed
LGTM aside from one minor nitpick

2024-03-16 17:42 UTC, notgull commented on src/lib.rs
> +        note = "use `is_err` in combination of is_hub instead, see documentation for `is_err`"
```suggestion
        note = "use `is_err` in combination of is_hup instead, see documentation for `is_err`"
```

2024-03-20 18:03 UTC, irvingoujAtDevolution commented
😢 , @notgull could you please help me look at the wine CI thing? I have no idea how that works

2024-03-21 05:03 UTC, notgull commented
Looks like a [spurious error](https://github.com/smol-rs/polling/actions/runs/8363127534/job/22895359605).

2024-03-21 05:04 UTC, notgull approved these changes
Thanks!

2024-03-21 05:04 UTC, merged