Add support for HermitOS
smol-rs/polling pull request #194
Opened 2024-02-25 18:13 UTC by notgull

HermitOS is a microkernel target aiming to provide a simple OS for
virtualized applications. It recently added support for the poll() and
eventfd() system calls, which means we can target it with our poll()
based backend.

Hermit does not have a traditional libc; instead it uses hermit-abi.
However rustix does not support using hermit-abi as its underlying
layer yet. So we have to build a shim layer until it does.

Closes #177
cc bytecodealliance/rustix#1012
cc @stlankes

2024-02-27 21:11 UTC, stlankes commented
Looks good from my side! However, we have an issue `last_os_error()` and it doesn't work like expected. But we are able to fix it. I  will give you a hit, it it works like expected.

2024-02-28 02:59 UTC, notgull commented
> Looks good from my side! However, we have an issue `last_os_error()` and it doesn't work like expected. But we are able to fix it. I will give you a hit, it it works like expected.

Could you elaborate? What error is being returned?

2024-02-29 09:01 UTC, stlankes commented
In `std` we determine the last error code in a different way and ignored `last_os_error`. We just don't use it. To solve it, we submit rust-lang/rust#121765. In the current stage, I would directly use [hermit-abi](https://github.com/hermit-os/hermit-rs/blob/main/hermit-abi/src/lib.rs#L342) to get the last error code.

2024-03-02 03:33 UTC, notgull commented
@stlankes I've fixed it to use `get_errno` instead of `last_os_error`, can you take another look?

2024-03-02 07:53 UTC, stlankes requested changes

2024-03-02 07:53 UTC, stlankes commented on src/poll.rs
>          if fd == -1 {
` if fd == -1 {`

You should use ` if fd < 0 {`. In our case, the return values could be another negative number.

2024-03-02 07:53 UTC, stlankes commented on src/poll.rs
>          if len == -1 {
See comments above. `if len < 0 {` is the correct way. All other parts are in my opinion correct.

2024-03-13 04:33 UTC, merged